
package com.vanesoft.vtrack.demonios.servicios.consultor.soapvtas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "scli_wsdl", targetNamespace = "urn:scli/wsdl", wsdlLocation = "http://192.168.1.32:32007?wsdl")
public class ScliWsdl
    extends Service
{

    private final static URL SCLIWSDL_WSDL_LOCATION;
    private final static WebServiceException SCLIWSDL_EXCEPTION;
    private final static QName SCLIWSDL_QNAME = new QName("urn:scli/wsdl", "scli_wsdl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.32:32007?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCLIWSDL_WSDL_LOCATION = url;
        SCLIWSDL_EXCEPTION = e;
    }

    public ScliWsdl() {
        super(__getWsdlLocation(), SCLIWSDL_QNAME);
    }

    public ScliWsdl(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCLIWSDL_QNAME, features);
    }

    public ScliWsdl(URL wsdlLocation) {
        super(wsdlLocation, SCLIWSDL_QNAME);
    }

    public ScliWsdl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCLIWSDL_QNAME, features);
    }

    public ScliWsdl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScliWsdl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScliWsdlPortType
     */
    @WebEndpoint(name = "scli_wsdlPort")
    public ScliWsdlPortType getScliWsdlPort() {
        return super.getPort(new QName("urn:scli/wsdl", "scli_wsdlPort"), ScliWsdlPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScliWsdlPortType
     */
    @WebEndpoint(name = "scli_wsdlPort")
    public ScliWsdlPortType getScliWsdlPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:scli/wsdl", "scli_wsdlPort"), ScliWsdlPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCLIWSDL_EXCEPTION!= null) {
            throw SCLIWSDL_EXCEPTION;
        }
        return SCLIWSDL_WSDL_LOCATION;
    }

}
