
package com.vanesoft.vtrack.demonios.servicios.consultor.soapvtas;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "scli_wsdlPortType", targetNamespace = "urn:scli/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScliWsdlPortType {


    /**
     * Pedidos con Eventos Nuevos
     * 
     * @param parametrosPedidos
     * @return
     *     returns java.util.List<com.vanesoft.vtrack.demonios.servicios.consultor.soapvtas.RespuestaPedido>
     */
    @WebMethod(operationName = "Pedidos")
    @WebResult(name = "PEDIDO", targetNamespace = "")
    @RequestWrapper(localName = "Pedidos", targetNamespace = "urn:scli/wsdl", className = "com.vanesoft.vtrack.demonios.servicios.consultor.soapvtas.Pedidos")
    @ResponseWrapper(localName = "respuestaPedidos", targetNamespace = "urn:scli/wsdl", className = "com.vanesoft.vtrack.demonios.servicios.consultor.soapvtas.RespuestaPedidos")
    public List<RespuestaPedido> pedidos(
        @WebParam(name = "parametrosPedidos", targetNamespace = "")
        ParametrosPedidos parametrosPedidos);

    /**
     * Eventos Nuevos del Pedido
     * 
     * @param parametrosEventos
     * @return
     *     returns java.util.List<com.vanesoft.vtrack.demonios.servicios.consultor.soapvtas.RespuestaEvento>
     */
    @WebMethod(operationName = "Eventos")
    @WebResult(name = "EVENTO", targetNamespace = "")
    @RequestWrapper(localName = "Eventos", targetNamespace = "urn:scli/wsdl", className = "com.vanesoft.vtrack.demonios.servicios.consultor.soapvtas.Eventos")
    @ResponseWrapper(localName = "respuestaEventos", targetNamespace = "urn:scli/wsdl", className = "com.vanesoft.vtrack.demonios.servicios.consultor.soapvtas.RespuestaEventos")
    public List<RespuestaEvento> eventos(
        @WebParam(name = "parametrosEventos", targetNamespace = "")
        ParametrosEventos parametrosEventos);

}
