
package com.vanesoft.vtrack.demonios.servicios.consultor.soapvtassimulacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSActualizadorService", targetNamespace = "http://implementacion.servicioactualizador.webservice.vtrack.vanesoft.com/", wsdlLocation = "http://localhost:8080/webservice.servicioactualizador/WSActualizador?wsdl")
public class WSActualizadorService
    extends Service
{

    private final static URL WSACTUALIZADORSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSACTUALIZADORSERVICE_EXCEPTION;
    private final static QName WSACTUALIZADORSERVICE_QNAME = new QName("http://implementacion.servicioactualizador.webservice.vtrack.vanesoft.com/", "WSActualizadorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice.servicioactualizador/WSActualizador?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSACTUALIZADORSERVICE_WSDL_LOCATION = url;
        WSACTUALIZADORSERVICE_EXCEPTION = e;
    }

    public WSActualizadorService() {
        super(__getWsdlLocation(), WSACTUALIZADORSERVICE_QNAME);
    }

    public WSActualizadorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSACTUALIZADORSERVICE_QNAME, features);
    }

    public WSActualizadorService(URL wsdlLocation) {
        super(wsdlLocation, WSACTUALIZADORSERVICE_QNAME);
    }

    public WSActualizadorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSACTUALIZADORSERVICE_QNAME, features);
    }

    public WSActualizadorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSActualizadorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSActualizador
     */
    @WebEndpoint(name = "WSActualizadorPort")
    public WSActualizador getWSActualizadorPort() {
        return super.getPort(new QName("http://implementacion.servicioactualizador.webservice.vtrack.vanesoft.com/", "WSActualizadorPort"), WSActualizador.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSActualizador
     */
    @WebEndpoint(name = "WSActualizadorPort")
    public WSActualizador getWSActualizadorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://implementacion.servicioactualizador.webservice.vtrack.vanesoft.com/", "WSActualizadorPort"), WSActualizador.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSACTUALIZADORSERVICE_EXCEPTION!= null) {
            throw WSACTUALIZADORSERVICE_EXCEPTION;
        }
        return WSACTUALIZADORSERVICE_WSDL_LOCATION;
    }

}
